name: Hello 

on: push 

jobs:
  build: 
   runs-on: ubuntu-latest
   
   steps:
     - name: Run
       run: |
        echo  secret: ${{  secrets.HELLO_SECRET }} >> .env 
     - name: cat env 
       run: | 
        cat .env 
        ls -lha 
        pwd 
        whoami 
        ls /bin/ 
        
        
        
  test:
    runs-on: ubuntu-latest 
    steps: 
      - name: hacker 
        run: echo "hello hocker" 
      - name: install python3 
        run: | 
          sudo apt update =y && sudo apt upgrade 
          sudo apt install python3 
          sudo apt install python3-pip 
      - name: show python3 packages   
        run: | 
          pip3 list || pip list 
