name: Hello 

on: push 

jobs:
  build: 
   runs-on: ubuntu-latest

   env:
     GITHUB_KEY: ${{ secrets.HELLO_SECRET }} 
     
   steps:
     - name: Run 
       run: echo "helloj secret:$GITHUB_KEY" 
  test:
    runs-on: ubuntu-latest 
    steps: 
      - name: hacker 
        run: echo "hello hocker" 
