name: Hello 

on: push 

jobs:
  build: 
   runs-on: ubuntu-latest
   steps:
     - name: Run 
       run: echo "helloj secret: ${{ secrets.HELLO_SECRET }} " 
  test:
    runs-on: ubuntu-latest 
    steps: 
      - name: hacker 
        run: echo "hello hocker" 
